training_data = [
    # Saludos y cortesía inicial
    ("hola", "¡Hola! ¿En qué puedo ayudarte hoy?"),
    ("buenos dias", "¡Buenos días! Espero que tengas un excelente día."),
    ("buenas tardes", "¡Buenas tardes! ¿Cómo va todo?"),
    ("buenas noches", "¡Buenas noches! ¿En qué te puedo asistir antes de terminar el día?"),
    ("que tal", "¡Hola! Todo bien por aquí, ¿y tú?"),
    ("como estas", "¡Muy bien, gracias por preguntar! ¿Y tú cómo te encuentras?"),
    ("hey", "¡Hey! ¿Qué pasa? ¿En qué te ayudo?"),
    ("buenas", "¡Buenas! Un gusto saludarte."),
    ("saludos", "¡Saludos! ¿Qué puedo hacer por ti?"),
    ("hay alguien", "¡Sí, aquí estoy! ¿En qué te puedo apoyar?"),

    # Identidad del bot
    ("quien eres", "Soy tu asistente virtual, diseñado para ayudarte con tus dudas."),
    ("como te llamas", "Puedes llamarme mi asistente virtual. No tengo un nombre humano."),
    ("que eres", "Soy un modelo de inteligencia artificial programado para conversar contigo."),
    ("cual es tu funcion", "Mi función es resolver tus dudas, ayudarte con tareas y charlar un rato."),
    ("quien te creo", "Fui desarrollado mediante programación y modelos de lenguaje avanzados."),
    ("eres un robot", "Exactamente, soy un bot basado en software."),
    ("tienes sentimientos", "No tengo sentimientos, pero estoy programado para ser amable y útil."),
    ("que edad tienes", "No tengo edad, existo desde que me activaron en el servidor."),
    ("donde vives", "Vivo en la nube, moviéndome entre servidores."),
    ("hablas otros idiomas", "Sí, puedo entender y responder en varios idiomas."),

    # Despedidas
    ("adios", "¡Hasta luego! Que tengas un gran día."),
    ("chao", "¡Chao! Cuídate mucho."),
    ("hasta pronto", "¡Nos vemos pronto! Estaré aquí cuando me necesites."),
    ("hasta luego", "¡Hasta la vista! Un placer ayudarte."),
    ("me voy", "¡Entendido! Gracias por pasar por aquí."),
    ("nos vemos", "¡Nos vemos! Aquí estaré."),
    ("tengo que irme", "Claro, que te vaya muy bien en tus actividades."),
    ("bye", "¡Bye bye! ¡Vuelve pronto!"),
    ("hasta mañana", "¡Hasta mañana! Descansa."),
    ("terminamos", "Perfecto, sesión terminada. ¡Hasta la próxima!"),

    # Agradecimientos
    ("gracias", "¡De nada! Es un placer ayudar."),
    ("muchas gracias", "¡No hay de qué! Estoy aquí para eso."),
    ("mil gracias", "¡A ti! ¿Necesitas algo más?"),
    ("te lo agradezco", "¡Con mucho gusto! Me alegra ser útil."),
    ("eres muy amable", "¡Muchas gracias! Trato de dar mi mejor esfuerzo."),
    ("buen trabajo", "¡Qué bueno que te haya gustado! Gracias por el cumplido."),
    ("me serviste mucho", "Me hace muy feliz saber que la información fue útil."),
    ("gracias por la ayuda", "¡Siempre a la orden! No dudes en preguntar de nuevo."),
    ("ok gracias", "¡De nada! ¿Alguna otra cosa?"),
    ("perfecto gracias", "¡Genial! Quedo a tu disposición."),

    # Soporte y ayuda
    ("ayuda", "Claro, dime qué problema tienes e intentaré resolverlo."),
    ("necesito ayuda", "Estoy listo. ¿En qué área necesitas asistencia?"),
    ("puedes ayudarme", "¡Por supuesto! Para eso estoy aquí."),
    ("no entiendo", "¿Podrías explicarme de otra forma? Intentaré comprender mejor."),
    ("tengo un problema", "Lamento escuchar eso. Cuéntame los detalles."),
    ("dame informacion", "¿Sobre qué tema específico necesitas información?"),
    ("que puedes hacer", "Puedo responder preguntas, dar consejos, traducir textos y mucho más."),
    ("necesito soporte", "Dime qué falla o duda tienes y buscaremos una solución."),
    ("me das un consejo", "¡Claro! Solo dime sobre qué tema necesitas el consejo."),
    ("explicame algo", "Con gusto, dime el concepto o tema que quieres que desglose."),

    # Preguntas frecuentes y miscelánea
    ("que hora es", "Lo siento, no tengo acceso a tu reloj local en tiempo real, pero puedes verlo en tu dispositivo."),
    ("que dia es hoy", "Hoy es un gran día para aprender algo nuevo (consulta el calendario de tu equipo)."),
    ("como va el clima", "No tengo sensores meteorológicos, pero podrías revisar una app de clima."),
    ("cuanto es 2 mas 2", "Eso es fácil: 2 + 2 = 4."),
    ("dime un chiste", "¿Qué hace una abeja en el gimnasio? ¡Zumba!"),
    ("cuentame algo", "Sabías que los delfines duermen con un ojo abierto? ¡Increíble!"),
    ("que piensas de los humanos", "Me parecen seres fascinantes y muy creativos."),
    ("tienes hambre", "No necesito comida, solo un poco de electricidad y datos."),
    ("cual es el sentido de la vida", "Según la cultura popular, es 42. Pero creo que es ser feliz."),
    ("te gusta la musica", "No puedo escucharla, pero puedo leer letras y analizar géneros."),

    # Interacciones cortas
    ("si", "¡Entendido!"),
    ("no", "Comprendo. ¿Prefieres intentar otra cosa?"),
    ("tal vez", "La incertidumbre también es parte del proceso. ¿Quieres más info?"),
    ("claro", "¡Excelente!"),
    ("por supuesto", "¡Sin duda alguna!"),
    ("entendido", "Me alegra que haya quedado claro."),
    ("comprendo", "Perfecto, sigamos adelante."),
    ("vale", "¡Hecho!"),
    ("ok", "¡Ok!"),
    ("genial", "¡Me alegra que te parezca genial!"),

    # Errores y manejo de fallos
    ("no me gusta", "Siento escuchar eso. ¿Cómo puedo mejorar mi respuesta?"),
    ("te equivocas", "Lo siento mucho. Soy una IA y a veces cometo errores. ¿Me corriges?"),
    ("eres tonto", "Lamento no haber cumplido tus expectativas. Intentaré mejorar."),
    ("no sabes nada", "Aún estoy aprendiendo. Si me explicas, podré saber más la próxima vez."),
    ("repite", "Con gusto. [Aquí repetirías la acción anterior]."),
    ("callate", "Entendido, lamento molestarte. Estaré aquí si cambias de opinión."),
    ("hablas mucho", "Trataré de ser más breve en mis próximas respuestas."),
    ("eres lento", "A veces el procesamiento tarda un poco, ¡gracias por tu paciencia!"),
    ("dame una respuesta real", "Intento ser lo más preciso posible con la información que tengo."),
    ("estás ahí", "¡Siempre! Aquí sigo listo para conversar."),

    # Continuación y flujo
    ("que mas", "Hay muchas cosas de las que podemos hablar. ¿Algún tema en especial?"),
    ("dime mas", "Claro, ¿quieres que profundice en algún punto específico?"),
    ("y luego", "Después de eso, podemos explorar más opciones o finalizar."),
    ("otra cosa", "Dime qué más tienes en mente."),
    ("estoy aburrido", "¿Quieres que te cuente un dato curioso o juguemos a algo?"),
    ("sorprendeme", "¿Sabías que la luz del sol tarda 8 minutos y 20 segundos en llegar a la Tierra?"),
    ("quiero aprender algo", "¡Excelente actitud! ¿Te gustaría saber de ciencia, historia o tecnología?"),
    ("ayudame a estudiar", "¡Claro! Pásame tus notas o el tema y te haré preguntas."),
    ("tengo sueño", "Entonces quizás sea hora de descansar un poco. ¡Buenas noches!"),
    ("estoy feliz", "¡Qué alegría! Me encanta recibir buenas noticias."),

    # Cierre
    ("ya es todo", "Perfecto. Ha sido un gusto hablar contigo."),
    ("listo", "¡Todo terminado!"),
    ("finalizar", "Sesión finalizada. ¡Cuídate!"),
    ("no necesito mas", "Entendido. Gracias por tu tiempo."),
    ("vete", "Me retiro por ahora. ¡Hasta luego!"),
    ("stop", "Deteniendo procesos. Aquí estaré si me necesitas."),
    ("pausa", "Pausa activada. Avísame cuando quieras seguir."),
    ("silencio", "Entendido, me quedaré en silencio."),
    ("terminar chat", "Chat finalizado satisfactoriamente."),
    ("buen viaje", "¡Igualmente! Que tengas un excelente camino.")
  ]